### ISSUE TITLE
The IEEE template introduces a lot of if/def noise.

### ISSUE THREAD

**Issue by tobiasgrosser** [opencompl/paper-template#18]
I am wondering if we can find ways to reduce this noise without adding even more abstractions. The more complex this repo becomes the more likely things break and the slower we can work with things. We use the ACM templates a lot more often than the IEEE templates so the common case we should optimize for is ACM. Even having some manual porting efforts for the IEEE template seems to be reasonable for me.

**Comment by Superty** [comment]
Done it seems
