### ISSUE TITLE
Add sections as single files

### ISSUE THREAD

**Issue by webmiche** [opencompl/paper-template#30]
In this template, we basically write all the text in the `paper.tex` file. This has the downside that one has to skim through a lot of text when wanting to find a particular section to work on.

In my thesis template, I had a folder `Chapters` that contained single files for each section (i.e. `01-intro.tex`, `06-conclusion.tex`), which all were imported into the equivalent of `paper.tex` in this template. Not sure how you feel about it, but to me, this structure is easier to work on.

Tagging some people to get their opinions: @tobiasgrosser @bollu @math-fehr @Superty @Dinistro

**Comment by Superty** [comment]
I am definitely in favour of putting the content of the paper into a different file from all the boilerplate.  Personally I prefer to keep all sections in one file though, mostly because I'm used to it and I can jump to section as easily as jumping to file in my editor. Also sometimes I want to make a nice transition from one section to another which is slightly easier when viewing both in the same file

**Comment by tobiasgrosser** [comment]
I would agree that it might make sense to put the boilerplate into a separate file. With respect to factoring out subsections into separate files, that is a subjective choice. I personally like to keep everything in a single file, as I typically navigate by searching to the term that I am interested in. That works best for me if everything is in a single file. I know that @goens

**Comment by tobiasgrosser** [comment]
I am happy to arrange a brainstorming how we can improve this template given that the deadline is now over.

**Comment by tobiasgrosser** [comment]
I moved some of the builerplate into separate .tex files. See #33. Does that seem like a step into the right direction?

**Comment by math-fehr** [comment]
To me, this makes a lot of sense!
I prefer having the boilerplate extracted from the main file, rather than having a single file for each section.
Having a single file for each section makes it harder to quickly move in the code!

**Comment by webmiche** [comment]
That's certainly a step in the right direction. As the consensus seems to be that most people prefer one file for the entire text, I guess we can leave this as is after merging #33. I agree that adding files for each section can be done on a per-project basis, if anyone prefers that.
